apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "asset-configuration"
spec:
  destination:
    namespace: "argocd"
    server: https://kubernetes.default.svc
  project: default
  source:
    path: services/asset-configuration
    repoURL: https://github.com/sadshwat/argocd-example.git
    targetRevision: master
  syncPolicy:
    automated: {}