apiVersion: v1
kind: Service
metadata:
  name: {{ include "asset-configuration.fullname" . }}
  labels:
    {{- include "asset-configuration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcport }}
      targetPort: grpcport
      protocol: TCP
      name: grpcport
  selector:
    {{- include "asset-configuration.selectorLabels" . | nindent 4 }}
