apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: processops-routing-service
spec:
  http:
  - match:
      - uri:
          prefix: /asset-configuration
    route:
      - destination:
          host: /asset-configuration
  - match:
      - uri:
          prefix: /piq-facility-provisioning-automation
    route: 
      - destination: 
          host: piq-facility-provisioning-automation